name: Deploy Node.js API

on:
  push:
    branches: [ main ]   # Déclenche le workflow sur chaque push dans "main"
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Ou la version que tu utilises

      - name: Install dependencies
        run: npm install

      - name: Run tests (si tu en as)
        run: npm test || echo "Pas de tests définis"